#################### default parameters ################################
# favicon
favicon = "images/favicon.png"
# logo
logo = "images/logo.svg"
logo_darkmode = "images/logo.svg"

# use `px` or `x` with logo_width, example: "100px".
# Note: logo_width is not work with .svg file
logo_width = "100px"
# if logo_webp set false, will not generate WEBP version of logo | default is true
logo_webp = true
# logo text will only show when logo is missing.
logo_text = "M..alu"

# purgeCSS
purge_css = true

# contact form action
contact_form_action = "#" # contact form works with [https://airform.io/] or [https://formspree.io]

# google tag manager, see https://developers.google.com/tag-manager/
google_adsense = "" # example: ca-pub-xxxxxxxxxxxxxxxx
google_tag_manager = "" # example: G-XXXXXXXXXX

# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>"

# Author
author = "Luc Van De Velde"

# copyright
copyright = "Copyright by M..Alu de 2023 au present"
theme_copyright = false

# Preloader
[preloader]
enable = true 
preloader = "images/preloader.gif" # use jpg, png, svg or gif format.

# contact info
[contact_info]
address = "Chemin de la Mude 83690 Salernes"
email = "m.alumenuiserie@gmail.com"
mobile = "+330787028912"

[metadata]
author = "M.. Alu a Salernes" 
description = "Pour embellir votre maison, intérieure & extérieure. Menuiserie PVC, ALU & BOIS. Venez voir notre site pour en apprendre plus." 
image = "images/favicon.png" # this image will be used as fallback if a page has no image of its own
keywords = ["M.. Alu", "Menuiserie", "Alu", "PVC", "Bois", "BTP","Cuisine","Parquet","Fenêtres","Portes","Verandas","Pergolas"] 

# google map
[google_map]
enable = true

embed_url = "https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d2890.6863394168126!2d6.216359496444148!3d43.57141852190968!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sfr!2sfr!4v1698763472514!5m2!1sfr!2sfr"

# Client Logo Slider 
[[logo_slider]]
URL = "http://examplesite.com"
logo = "images/clients-logo/client-logo-1.png"

[[logo_slider]]
URL = "#"
logo = "images/clients-logo/client-logo-2.png"

[[logo_slider]]
URL = "http://examplesite.com"
logo = "images/clients-logo/client-logo-3.png"

[[logo_slider]]
URL = "#"
logo = "images/clients-logo/client-logo-4.png"

[[logo_slider]]
URL = "http://examplesite.com"
logo = "images/clients-logo/client-logo-5.png"

[[logo_slider]]
URL = "#"
logo = "images/clients-logo/client-logo-1.png"

[[logo_slider]]
URL = "http://examplesite.com"
logo = "images/clients-logo/client-logo-2.png"

[[logo_slider]]
URL = "#"
logo = "images/clients-logo/client-logo-3.png"

[[logo_slider]]
URL = "http://examplesite.com"
logo = "images/clients-logo/client-logo-4.png"

[[logo_slider]]
URL = "#"
logo = "images/clients-logo/client-logo-5.png"

############################# social site ########################
[[social]]
icon = "ti-facebook" # themify icon https =themify.me/themify-icons
link = "#" 
title = "facebook" 

[[social]]
icon = "ti-twitter" # themify icon - https://themify.me/themify-icons
link = "#" 
title = "twitter" 

[[social]]
icon = "ti-instagram" # themify icon - https://themify.me/themify-icons
link = "#" 
title = "instagram" 

[[social]]
icon = "ti-linkedin" # themify icon - https://themify.me/themify-icons
link = "#" 
title = "linkedin"
